import 'package:my_app/models/responses/cards/response-tarot-core.dart';

import 'enums/enum-tarot-product.dart';

class TarotList {
  List<ResponseTarotCore> cards = [
    ResponseTarotCore(title: 'The Fool', description: '', imageName: '00-TheFool.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'The Magician', description: '', imageName: '01-TheMagician.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'The HighPriestess', description: '', imageName: '02-TheHighPriestess.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'The Empress', description: '', imageName: '03-TheEmpress.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'The Emperor', description: '', imageName: '04-TheEmperor.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'The Hierophant', description: '', imageName: '05-TheHierophant.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'The Lovers', description: '', imageName: '06-TheLovers.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'The Chariot', description: '', imageName: '07-TheChariot.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Strength', description: '', imageName: '08-Strength.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'The Hermit', description: '', imageName: '09-TheHermit.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Wheel Of Fortune', description: '', imageName: '10-WheelOfFortune.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Justice', description: '', imageName: '11-Justice.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'The HangedMan', description: '', imageName: '12-TheHangedMan.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Death', description: '', imageName: '13-Death.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Temperance', description: '', imageName: '14-Temperance.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'The Devil', description: '', imageName: '15-TheDevil.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'The Tower', description: '', imageName: '16-TheTower.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'The Star', description: '', imageName: '17-TheStar.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'The Moon', description: '', imageName: '18-TheMoon.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'The Sun', description: '', imageName: '19-TheSun.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Judgement', description: '', imageName: '20-Judgement.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'The World', description: '', imageName: '21-TheWorld.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Cups 01', description: '', imageName: 'Cups01.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Cups 02', description: '', imageName: 'Cups02.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Cups 03', description: '', imageName: 'Cups03.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Cups 04', description: '', imageName: 'Cups04.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Cups 05', description: '', imageName: 'Cups05.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Cups 06', description: '', imageName: 'Cups06.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Cups 07', description: '', imageName: 'Cups07.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Cups 08', description: '', imageName: 'Cups08.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Cups 09', description: '', imageName: 'Cups09.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Cups 10', description: '', imageName: 'Cups10.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Cups 11', description: '', imageName: 'Cups11.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Cups 12', description: '', imageName: 'Cups12.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Cups 13', description: '', imageName: 'Cups13.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Cups 14', description: '', imageName: 'Cups14.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Pentacles 01', description: '', imageName: 'Pentacles01.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Pentacles 02', description: '', imageName: 'Pentacles02.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Pentacles 03', description: '', imageName: 'Pentacles03.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Pentacles 04', description: '', imageName: 'Pentacles04.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Pentacles 05', description: '', imageName: 'Pentacles05.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Pentacles 06', description: '', imageName: 'Pentacles06.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Pentacles 07', description: '', imageName: 'Pentacles07.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Pentacles 08', description: '', imageName: 'Pentacles08.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Pentacles 09', description: '', imageName: 'Pentacles09.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Pentacles 10', description: '', imageName: 'Pentacles10.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Pentacles 11', description: '', imageName: 'Pentacles11.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Pentacles 12', description: '', imageName: 'Pentacles12.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Pentacles 13', description: '', imageName: 'Pentacles13.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Pentacles 14', description: '', imageName: 'Pentacles14.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Swords 01', description: '', imageName: 'Swords01.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Swords 02', description: '', imageName: 'Swords02.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Swords 03', description: '', imageName: 'Swords03.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Swords 04', description: '', imageName: 'Swords04.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Swords 05', description: '', imageName: 'Swords05.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Swords 06', description: '', imageName: 'Swords06.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Swords 07', description: '', imageName: 'Swords07.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Swords 08', description: '', imageName: 'Swords08.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Swords 09', description: '', imageName: 'Swords09.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Swords 10', description: '', imageName: 'Swords10.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Swords 11', description: '', imageName: 'Swords11.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Swords 12', description: '', imageName: 'Swords12.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Swords 13', description: '', imageName: 'Swords13.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Swords 14', description: '', imageName: 'Swords14.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Wands 01', description: '', imageName: 'Wands01.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Wands 02', description: '', imageName: 'Wands02.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Wands 03', description: '', imageName: 'Wands03.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Wands 04', description: '', imageName: 'Wands04.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Wands 05', description: '', imageName: 'Wands05.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Wands 06', description: '', imageName: 'Wands06.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Wands 07', description: '', imageName: 'Wands07.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Wands 08', description: '', imageName: 'Wands08.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Wands 09', description: '', imageName: 'Wands09.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Wands 10', description: '', imageName: 'Wands10.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Wands 11', description: '', imageName: 'Wands11.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Wands 12', description: '', imageName: 'Wands12.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Wands 13', description: '', imageName: 'Wands13.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Wands 14', description: '', imageName: 'Wands14.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
  ];
}