import 'package:my_app/models/cards/response-tarot-core.dart';

import 'enums/enum-tarot-product.dart';

class TarotList {
  List<ResponseTarotCore> cards = [
    ResponseTarotCore(title: '00-TheFool.png', description: '', imageName: '00-TheFool.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: '01-TheMagician.png', description: '', imageName: '01-TheMagician.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: '02-TheHighPriestess.png', description: '', imageName: '02-TheHighPriestess.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: '03-TheEmpress.png', description: '', imageName: '03-TheEmpress.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: '04-TheEmperor.png', description: '', imageName: '04-TheEmperor.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: '05-TheHierophant.png', description: '', imageName: '05-TheHierophant.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: '06-TheLovers.png', description: '', imageName: '06-TheLovers.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: '07-TheChariot.png', description: '', imageName: '07-TheChariot.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: '08-Strength.png', description: '', imageName: '08-Strength.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: '09-TheHermit.png', description: '', imageName: '09-TheHermit.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: '10-WheelOfFortune.png', description: '', imageName: '10-WheelOfFortune.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: '11-Justice.png', description: '', imageName: '11-Justice.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: '12-TheHangedMan.png', description: '', imageName: '12-TheHangedMan.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: '13-Death.png', description: '', imageName: '13-Death.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: '14-Temperance.png', description: '', imageName: '14-Temperance.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: '15-TheDevil.png', description: '', imageName: '15-TheDevil.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: '16-TheTower.png', description: '', imageName: '16-TheTower.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: '17-TheStar.png', description: '', imageName: '17-TheStar.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: '18-TheMoon.png', description: '', imageName: '18-TheMoon.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: '19-TheSun.png', description: '', imageName: '19-TheSun.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: '20-Judgement.png', description: '', imageName: '20-Judgement.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: '21-TheWorld.png', description: '', imageName: '21-TheWorld.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Cups01.png', description: '', imageName: 'Cups01.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Cups02.png', description: '', imageName: 'Cups02.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Cups03.png', description: '', imageName: 'Cups03.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Cups04.png', description: '', imageName: 'Cups04.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Cups05.png', description: '', imageName: 'Cups05.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Cups06.png', description: '', imageName: 'Cups06.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Cups07.png', description: '', imageName: 'Cups07.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Cups08.png', description: '', imageName: 'Cups08.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Cups09.png', description: '', imageName: 'Cups09.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Cups10.png', description: '', imageName: 'Cups10.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Cups11.png', description: '', imageName: 'Cups11.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Cups12.png', description: '', imageName: 'Cups12.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Cups13.png', description: '', imageName: 'Cups13.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Cups14.png', description: '', imageName: 'Cups14.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Pentacles01.png', description: '', imageName: 'Pentacles01.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Pentacles02.png', description: '', imageName: 'Pentacles02.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Pentacles03.png', description: '', imageName: 'Pentacles03.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Pentacles04.png', description: '', imageName: 'Pentacles04.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Pentacles05.png', description: '', imageName: 'Pentacles05.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Pentacles06.png', description: '', imageName: 'Pentacles06.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Pentacles07.png', description: '', imageName: 'Pentacles07.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Pentacles08.png', description: '', imageName: 'Pentacles08.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Pentacles09.png', description: '', imageName: 'Pentacles09.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Pentacles10.png', description: '', imageName: 'Pentacles10.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Pentacles11.png', description: '', imageName: 'Pentacles11.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Pentacles12.png', description: '', imageName: 'Pentacles12.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Pentacles13.png', description: '', imageName: 'Pentacles13.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Pentacles14.png', description: '', imageName: 'Pentacles14.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Swords01.png', description: '', imageName: 'Swords01.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Swords02.png', description: '', imageName: 'Swords02.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Swords03.png', description: '', imageName: 'Swords03.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Swords04.png', description: '', imageName: 'Swords04.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Swords05.png', description: '', imageName: 'Swords05.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Swords06.png', description: '', imageName: 'Swords06.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Swords07.png', description: '', imageName: 'Swords07.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Swords08.png', description: '', imageName: 'Swords08.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Swords09.png', description: '', imageName: 'Swords09.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Swords10.png', description: '', imageName: 'Swords10.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Swords11.png', description: '', imageName: 'Swords11.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Swords12.png', description: '', imageName: 'Swords12.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Swords13.png', description: '', imageName: 'Swords13.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Swords14.png', description: '', imageName: 'Swords14.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Wands01.png', description: '', imageName: 'Wands01.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Wands02.png', description: '', imageName: 'Wands02.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Wands03.png', description: '', imageName: 'Wands03.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Wands04.png', description: '', imageName: 'Wands04.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Wands05.png', description: '', imageName: 'Wands05.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Wands06.png', description: '', imageName: 'Wands06.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Wands07.png', description: '', imageName: 'Wands07.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Wands08.png', description: '', imageName: 'Wands08.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Wands09.png', description: '', imageName: 'Wands09.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Wands10.png', description: '', imageName: 'Wands10.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Wands11.png', description: '', imageName: 'Wands11.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Wands12.png', description: '', imageName: 'Wands12.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Wands13.png', description: '', imageName: 'Wands13.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
    ,ResponseTarotCore(title: 'Wands14.png', description: '', imageName: 'Wands14.png', enumTarotProduct: EnumTarotProduct.riderWaited) 
  ];
}